# Generated by Django 5.2.11 on 2026-02-11 15:28

from django.db import migrations, models

from baserow.contrib.builder.compat.graph_migrator import PageGraphMigrator
from baserow.core.utils import grouper


def forward(apps, schema_editor):
    Page = apps.get_model("builder", "Page")
    Element = apps.get_model("builder", "element")

    pages_iter = Page.objects.all().only("id", "graph").iterator(chunk_size=500)
    for pages in grouper(500, pages_iter):
        for page in pages:
            page_elements = Element.objects.filter(page=page).only(
                "id", "order", "parent_element_id"
            )
            serialized_elements = PageGraphMigrator.serialize_page_elements(
                page_elements
            )
            page.graph = PageGraphMigrator(serialized_elements).to_graph()
        Page.objects.bulk_update(pages, ["graph"])


def reverse(apps, schema_editor):
    Page = apps.get_model("builder", "Page")
    Element = apps.get_model("builder", "element")

    pages_iter = Page.objects.all().only("id", "graph").iterator(chunk_size=500)
    for pages in grouper(500, pages_iter):
        for page in pages:
            for element_id, info in page.graph.items():
                if element_id == "0":
                    continue
                # TODO: figure out how to re-apply the `order`.
                if children := info.get("children", []):
                    # TODO: set `place_in_container` once it's supported.
                    Element.objects.filter(id__in=children).update(
                        parent_element_id=element_id, place_in_container=""
                    )


class Migration(migrations.Migration):
    dependencies = [
        ("builder", "0067_slackwritemessageworkflowaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="graph",
            field=models.JSONField(
                default=dict,
                help_text="A JSON serialized graph containing the points and edges.",
            ),
        ),
        migrations.RunPython(forward, reverse),
        migrations.AlterModelOptions(
            name="element",
            options={"ordering": ("id",)},
        ),
        migrations.RemoveField(
            model_name="element",
            name="order",
        ),
        migrations.RemoveField(
            model_name="element",
            name="parent_element",
        ),
        migrations.RemoveField(
            model_name="element",
            name="place_in_container",
        ),
    ]
