# Generated by Django 5.2.11 on 2026-02-09 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0001_squashed_0023_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationworkflow',
            name='graph',
            field=models.JSONField(default=dict, help_text='A JSON serialized graph containing the points and edges.'),
        ),
    ]
