# Generated by Django 5.2.11 on 2026-02-10 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0024_automationworkflowhistory_event_payload_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationworkflowhistory',
            name='simulate_until_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='simulation_histories', to='automation.automationnode'),
        ),
    ]
